name: Bug Report
description: 버그를 고칠 수 있도록 도와주세요!
title: "[Bug] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        버그 제보를 해주셔서 감사합니다!
  - type: textarea
    id: description
    attributes:
      label: 버그 내용
      description: 발견된 버그와 관련된 내용을 적어주세요
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: howtofix
    attributes:
      label: 버그 수정
      description: 버그를 어떻게 수정할지와 수정 후 예상되는 결과를 적어주세요!
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
  - type: textarea
    id: additional
    attributes:
      label: 추가 내용
      description: 추가적으로 적어주실 내용을 부탁드립니다!
